version: '3'
services:
  redisdb:
    image: redis
    volumes:
      - redis-data:/data
  web:
    depends_on:
      - redisdb
    build: .
    ports:
      - "5000:8080"
    environment:
      REDIS_HOST: redisdb
      REDIS_PORT: 6379
volumes:
  redis-data: